import 'package:get_it/get_it.dart';
import 'package:injectable/injectable.dart';

import 'package:frontend/config/injection_container.config.dart'; // generated by flutter pub run build_runner

final getIt = GetIt.instance;

@InjectableInit()
void configureDependencies() => getIt.init(); // generated by flutter pub run build_runner