import 'package:get_it/get_it.dart';
import 'package:injectable/injectable.dart';

import 'package:frontend/config/injection_container.config.dart'; // generated by flutter pub run build_runner

/// Global service locator instance used across the app.
///
/// Registered dependencies are resolved through this `GetIt` container.
final getIt = GetIt.instance;

/// Bootstraps dependency injection wiring generated by `injectable`.
///
/// Call this once during app startup to register all modules and services.
@InjectableInit()
void configureDependencies() => getIt.init(); // generated by flutter pub run build_runner
